spring:
  application:
    name: service-service-1
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/monitor
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
common:
  jwt:
    bootstrap: true
  oshi:
    bootstrap: true
